package net.multigesture.kanama.processor

// The platform-neutral script model: the annotation-derived description of a @ScriptClass
// (and @RegisterClass) — its properties, methods, virtuals, signals — independent of how
// any one platform marshals or emits it. The KanamaProcessor builds these from the KSP
// symbol API; the JVM CodeEmitter/ScriptCodeEmitter consume them to generate registrars.
//
// Phase 3.1 (script-model-unification-design.md) turns this into the single source of
// truth for desktop/Android/iOS: it will be serialized (JSON) and consumed by the iOS
// build instead of the parseIosScript regex parser.
//
// NOTE (Phase 3.1 sub-step 1b, not yet done): ArgModel.readFromScratch/readPtrcallArg
// below still emit JVM (MemorySegment/ptrcall) codegen as strings — they are the one
// platform-specific bleed left in the model. They move to the JVM emitter side as the
// model is fully neutralized for serialization; kept here now so this extraction stays a
// byte-identical relocation.

internal data class ClassModel(
    val simpleName: String,
    val fqName: String,
    val parentClassName: String,
    val isTool: Boolean,
    val methods: List<MethodModel>,
    val properties: List<PropertyModel>,
    val virtuals: List<VirtualModel>,
    val signals: List<SignalModel>,
)

internal data class SignalModel(
    val godotName: String,
    val args: List<ArgModel>,
)

internal enum class MethodKind { REGULAR, PROPERTY_GETTER, PROPERTY_SETTER }

internal data class MethodModel(
    val kotlinName: String,
    val godotName: String,
    val returnType: TypeMapping?,
    val args: List<ArgModel>,
    val kind: MethodKind,
    val rpc: RpcModel? = null,
    /** For property accessors: the property's Kotlin name. */
    val propertyKotlinName: String? = null,
)

internal data class RpcModel(
    val mode: Int,
    val callLocal: Boolean,
    val transferMode: Int,
    val channel: Int,
)

internal data class ArgModel(
    val name: String,
    val type: TypeMapping,
    val objectWrapperFqName: String? = null,
    val nullable: Boolean = false,
    val hasDefault: Boolean = false,
) {
    /** Neutral: the Kotlin type the arg surfaces as (object wrapper FQN or mapped type). */
    val kotlinType: String
        get() = (objectWrapperFqName ?: type.kotlinType) + if (nullable) "?" else ""
}

// ArgModel's JVM-emit codegen (readFromScratch/readPtrcallArg/signalEmitValueExpr) lives
// with the JVM emitter in KanamaProcessor.kt as extension functions — not on the model —
// so the model stays a pure, serializable data holder (Phase 3.1).

internal data class PropertyModel(
    val kotlinName: String,
    val godotName: String,
    val type: TypeMapping,
    val isMutable: Boolean,
    val hint: Int = 0,
    val hintString: String = "",
    val usage: Int = 6,
)

internal data class VirtualModel(
    val virtualName: String,
    /** Name of the generated static upcall function (e.g. `callReady`). */
    val callFunctionName: String,
    /** Kotlin method to invoke on the user instance. */
    val kotlinMethodName: String,
    /** Ptrcall-convention args passed by Godot when invoking the virtual. */
    val args: List<ArgModel> = emptyList(),
    /**
     * Return type for value-returning virtuals (e.g. `_get_minimum_size` ->
     * Vector2). `null` for `void` virtuals (all the lifecycle ones). Set for
     * `@OverrideVirtual` declarations; drives return marshalling in
     * `dispatchCall` and the reported `return_type` in the method list.
     */
    val returnType: TypeMapping? = null,
)

// ---------- @ScriptClass models ----------

internal data class ScriptModel(
    val simpleName: String,
    val fqName: String,
    val attachTo: String,
    val isTool: Boolean,
    val isGlobalClass: Boolean,
    val properties: List<ScriptPropertyModel>,
    val toolButtons: List<ToolButtonModel>,
    val virtuals: List<VirtualModel>,
    val methods: List<MethodModel>,
    val signals: List<SignalModel>,
)

internal data class ToolButtonModel(
    val propertyName: String,
    val text: String,
    val icon: String,
    val method: MethodModel,
) {
    val hintString: String
        get() = if (icon.isEmpty()) text else "$text,$icon"
}

/**
 * Narrow Kotlin scalar surfaced for a 64-bit Godot Variant slot. Godot floats
 * and ints are always 64-bit on the wire; a `kotlin.Float`/`kotlin.Int`
 * property maps to Variant FLOAT/INT with widening on get and narrowing on
 * set, generated by the JVM emitter. The iOS emitter keeps such properties at
 * their Kotlin default (warned), pending an ios-runtime conversion path.
 */
internal enum class NarrowScalar(
    val kotlinType: String,
    val zeroLiteral: String,
    /** Appended when the narrow Kotlin value flows out to a 64-bit slot. */
    val toWide: String,
    /** Appended when a 64-bit slot value is assigned into the Kotlin field. */
    val fromWide: String,
) {
    FLOAT32("Float", "0f", ".toDouble()", ".toFloat()"),
    INT32("Int", "0", ".toLong()", ".toInt()"),
}

internal data class ScriptPropertyModel(
    val kotlinName: String,
    val godotName: String,
    val type: TypeMapping,
    val isMutable: Boolean,
    val hint: Int = 0,
    val hintString: String = "",
    val defaultLiteral: String? = null,
    val exportCategory: ScriptPropertyGroupModel? = null,
    val exportGroup: ScriptPropertyGroupModel? = null,
    val exportSubgroup: ScriptPropertyGroupModel? = null,
    val usage: Int = 6,
    val objectWrapperFqName: String? = null,
    val arrayElementWrapperFqName: String? = null,
    val customScriptFqName: String? = null,
    val arrayElementCustomScriptFqName: String? = null,
    val customScriptIsResource: Boolean = false,
    val arrayElementCustomScriptIsResource: Boolean = false,
    val arrayElementString: Boolean = false,
    /**
     * Source-level nullability of the property type. The JVM emitter does not need it
     * (VariantConverters handle null), but the iOS emitter does: an object-typed
     * `@ScriptProperty` delivers `null` for a 0 handle only when the Kotlin field is
     * nullable. Phase 3.2 ([IosScriptCodeEmitter]).
     */
    val nullable: Boolean = false,
    /** Set for kotlin.Float / kotlin.Int properties (Variant slot stays 64-bit). */
    val narrow: NarrowScalar? = null,
)

internal data class ScriptPropertyGroupModel(
    val name: String,
    val prefix: String,
    val usage: Int,
)

internal data class ScriptPropertyTypeModel(
    val type: TypeMapping,
    val hint: Int = 0,
    val hintString: String = "",
    val objectWrapperFqName: String? = null,
    val arrayElementWrapperFqName: String? = null,
    val customScriptFqName: String? = null,
    val arrayElementCustomScriptFqName: String? = null,
    val customScriptIsResource: Boolean = false,
    val arrayElementCustomScriptIsResource: Boolean = false,
    val arrayElementString: Boolean = false,
    val narrow: NarrowScalar? = null,
)

internal data class ScriptClassTypeInfo(
    val fqName: String,
    val simpleName: String,
    val attachTo: String,
    val isGlobalClass: Boolean,
) {
    val isExportableResource: Boolean
        get() = isGlobalClass && attachTo == "Resource"
    val isExportableGlobal: Boolean
        get() = isGlobalClass
    val propertyHint: Int
        get() = if (isExportableResource) 17 else 34
}
